[package]
name = "cov_matrix"
version = "0.1.0"
authors = ["llesage <louis.lesage@umontreal.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
